### ISSUE TITLE
PALS Package missing dependancies when installed

### ISSUE THREAD

**Issue by kmcluskey** [glasgowcompbio/PALS#13]
neo4j, statsmodel, loguru

**Comment by joewandy** [comment]
Need to describe the dependencies in readme (see issue #17)

**Comment by joewandy** [comment]
Need to modify setup.py to specify the dependency correctly, see https://discuss.streamlit.io/t/running-streamlit-inside-my-own-executable-with-the-click-module/1198/4

**Comment by joewandy** [comment]
Fixed in commit #da2ca52620c2eb58d1880775631965c6416482c0
