### ISSUE TITLE
Setup Neo4j (Reactome) on the server

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/PALS#26]
We need to set up a Neo4j (Reactome) instance on the server.  See https://github.com/glasgowcompbio/PALS/blob/master/setup_guide.md.

**Comment by RonanDaly** [comment]
Version 4 is the latest - do you know if this works, or do we have to use 3?

**Comment by RonanDaly** [comment]
Done, taking about 800 MB after a pals query.
