### ISSUE TITLE
Google finding wrong canonical url for page

### ISSUE THREAD

**Issue by RonanDaly** [glasgowcompbio/PALS#31]
Google is selecting https://awesome-streamlit.org/ as the canonical URL for the root page. I've set https://pals.glasgowcompbio.org/ in the HTTP headers, but there's a conflict here. Need to find out why it's associating the wrong URL with the page. I believe this is stopping the page from being indexed.

**Comment by joewandy** [comment]
Maybe best to create a static page describing PALS (see issue #20 ), and add a link to the app from there. That will be indexed for sure.

**Comment by joewandy** [comment]
1. We already have a static page: https://glasgowcompbio.github.io/PALS. It is a github static page, created by github from the readme file. We can probably use a custom domain name (http://pals.glasgowcompbio.org/) for it? See this link https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site.
2. Then change the URL for the current streamlit app at http://pals.glasgowcompbio.org to something else, and link to that from the static page in (1).
