### ISSUE TITLE
Add example data for MF and Mass2Motif data

### ISSUE THREAD

**Issue by RonanDaly** [glasgowcompbio/PALS#38]
We have examples for the pathways, but no example to run for the GNPS stuff. We should have some examples here that are easy for a reviewer to run.

**Comment by RonanDaly** [comment]
Okay, I didn't see the examples! Closing.

**Comment by joewandy** [comment]
I want to add a **Load example data** button, but it seems pretty difficult to do in Streamlit, since it is annoyingly restrictive

**Comment by RonanDaly** [comment]
I was just going to put that as an Issue!
